const express=require('express');
const bcrypt=require('bcryptjs');
const rateLimit=require('express-rate-limit');
const multer=require('multer');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const {z}=require('zod');
const {uploadDir}=require('./paths');
const db=require('./db');
const {sign,setSessionCookie,clearSessionCookie,requireAuth,requireSameOrigin}=require('./auth');
const api=express.Router();
const ROLES=['SUPER_ADMIN','EVENT_MANAGER','CONTENT_MANAGER'];
const PERMS={
 SUPER_ADMIN:new Set(['events','activities','registrations','team','content','gallery','logs','admins','settings']),
 EVENT_MANAGER:new Set(['events','registrations:read','gallery','activities:read']),
 CONTENT_MANAGER:new Set(['activities','registrations:read','team','content','settings'])
};
const allow=p=>(req,res,next)=>PERMS[req.admin?.role]?.has(p)?next():res.status(403).json({error:'Permission denied'});
const guard=[requireAuth,requireSameOrigin];
const validate=s=>(req,res,next)=>{const r=s.safeParse(req.body);if(!r.success)return res.status(400).json({error:'Validation failed',details:r.error.issues});req.body=r.data;next()};
const parse=v=>{try{return typeof v==='string'?JSON.parse(v||'[]'):v||[]}catch{return[]}};
const audit=(req,a,r,d)=>db.logActivity({id:req.admin?.sub,name:req.admin?.name||req.admin?.email||'Admin'},a,d,r);
const eventOut=r=>({...r,published:!!r.published,featured:!!r.featured,status:r.status||'UPCOMING',body:parse(r.body),gallery:parse(r.gallery),poster:r.poster||null});
const safeUrl=v=>{if(!v)return true;try{return ['http:','https:'].includes(new URL(v).protocol)}catch{return v.startsWith('/img/')||v.startsWith('/uploads/')}};

const loginLimiter=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:'draft-8',legacyHeaders:false});
api.post('/manage/auth/login',loginLimiter,validate(z.object({email:z.string().email().max(160),password:z.string().min(1).max(200)})),(req,res)=>{
 const a=db.prepare("SELECT * FROM admins WHERE email=? COLLATE NOCASE AND status='ACTIVE'").get(req.body.email.trim().toLowerCase());
 if(!a||!bcrypt.compareSync(req.body.password,a.password_hash))return res.status(401).json({error:'Invalid email or password.'});
 db.prepare("UPDATE admins SET last_login_at=datetime('now') WHERE id=?").run(a.id);
 setSessionCookie(res,sign(a));res.json({admin:{id:a.id,name:a.name,email:a.email,role:a.role,profile_image:a.profile_image}});
});
api.post('/manage/auth/logout',...guard,(req,res)=>{clearSessionCookie(res);res.status(204).end()});
api.get('/manage/auth/me',...guard,(req,res)=>{const a=db.prepare("SELECT id,name,email,role,profile_image,status,created_at,last_login_at FROM admins WHERE id=?").get(req.admin.sub);if(!a||a.status!=='ACTIVE')return res.status(401).json({error:'Inactive account'});req.admin.name=a.name;req.admin.email=a.email;req.admin.role=a.role;res.json({admin:a})});

const manage=express.Router();manage.use(...guard);
manage.get('/dashboard',(req,res)=>{
 const today=new Date().toISOString().slice(0,10);
 const stats={totalEvents:db.prepare('SELECT COUNT(*) c FROM events').get().c,upcomingEvents:db.prepare("SELECT COUNT(*) c FROM events WHERE event_date>=? AND status!='COMPLETED'").get(today).c,totalActivities:db.prepare('SELECT COUNT(*) c FROM activities WHERE visible=1').get().c,totalJoinRequests:db.prepare('SELECT COUNT(*) c FROM registrations').get().c,totalTeamMembers:db.prepare('SELECT COUNT(*) c FROM team_members WHERE active=1').get().c,totalAdmins:db.prepare("SELECT COUNT(*) c FROM admins WHERE status='ACTIVE'").get().c};
 res.json({stats,recentRegistrations:db.prepare('SELECT id,name,email,year,status,created_at FROM registrations ORDER BY id DESC LIMIT 8').all(),recentLogs:db.prepare('SELECT * FROM activity_logs ORDER BY id DESC LIMIT 8').all()});
});
const eventSchema=z.object({title:z.string().min(1).max(160),description:z.string().max(5000).default(''),category:z.string().min(1).max(60),event_date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),start_time:z.string().max(20).default(''),end_time:z.string().max(20).default(''),event_time:z.string().max(100).default(''),venue:z.string().max(180).default(''),reg_link:z.string().max(500).default(''),poster:z.string().max(500).default(''),summary:z.string().max(1000).default(''),body:z.array(z.string()).default([]),gallery:z.array(z.object({src:z.string(),caption:z.string().optional().default('')})).default([]),featured:z.boolean().default(false),published:z.boolean().default(true),status:z.enum(['DRAFT','UPCOMING','ONGOING','COMPLETED']).default('UPCOMING')});
manage.get('/events',allow('events'),(_,res)=>res.json(db.prepare('SELECT * FROM events ORDER BY event_date DESC,id DESC').all().map(eventOut)));
manage.post('/events',allow('events'),validate(eventSchema),(req,res)=>{const e=req.body;let slug=e.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'event';let n=1,base=slug;while(db.prepare('SELECT id FROM events WHERE slug=?').get(slug))slug=base+'-'+n++;const i=db.prepare('INSERT INTO events(slug,title,description,category,event_date,event_time,start_time,end_time,venue,reg_link,poster,summary,body,gallery,featured,published,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(slug,e.title,e.description,e.category,e.event_date,e.event_time,e.start_time,e.end_time,e.venue,safeUrl(e.reg_link)?e.reg_link:'',safeUrl(e.poster)?e.poster:'',e.summary,JSON.stringify(e.body),JSON.stringify(e.gallery),e.featured?1:0,e.published?1:0,e.status);audit(req,'event_created','events',e.title);res.status(201).json({id:i.lastInsertRowid,slug})});
manage.put('/events/:id',allow('events'),validate(eventSchema),(req,res)=>{const e=req.body;if(!db.prepare('SELECT id FROM events WHERE id=?').get(req.params.id))return res.status(404).json({error:'Event not found'});db.prepare("UPDATE events SET title=?,description=?,category=?,event_date=?,event_time=?,start_time=?,end_time=?,venue=?,reg_link=?,poster=?,summary=?,body=?,gallery=?,featured=?,published=?,status=?,updated_at=datetime('now') WHERE id=?").run(e.title,e.description,e.category,e.event_date,e.event_time,e.start_time,e.end_time,e.venue,safeUrl(e.reg_link)?e.reg_link:'',safeUrl(e.poster)?e.poster:'',e.summary,JSON.stringify(e.body),JSON.stringify(e.gallery),e.featured?1:0,e.published?1:0,e.status,req.params.id);audit(req,'event_updated','events',e.title);res.json({ok:true})});
manage.delete('/events/:id',allow('events'),(req,res)=>{const e=db.prepare('SELECT title FROM events WHERE id=?').get(req.params.id);if(!e)return res.status(404).json({error:'Event not found'});db.prepare('DELETE FROM events WHERE id=?').run(req.params.id);audit(req,'event_deleted','events',e.title);res.status(204).end()});
manage.patch('/events/:id/publish',allow('events'),validate(z.object({published:z.boolean()})),(req,res)=>{db.prepare("UPDATE events SET published=?,updated_at=datetime('now') WHERE id=?").run(req.body.published?1:0,req.params.id);audit(req,'event_publish_toggle','events',String(req.params.id));res.json({ok:true})});

const activitySchema=z.object({title:z.string().min(1).max(160),short_description:z.string().max(1000).default(''),activity_date:z.string().default(''),category:z.string().max(60).default('GENERAL'),status:z.string().max(30).default('VISIBLE'),url:z.string().max(500).default(''),sort_order:z.coerce.number().int().min(0).default(0),visible:z.boolean().default(true)});
manage.get('/activities',allow('activities'),(_,res)=>res.json(db.prepare('SELECT * FROM activities ORDER BY sort_order,id').all()));
manage.post('/activities',allow('activities'),validate(activitySchema),(req,res)=>{const a=req.body,i=db.prepare('INSERT INTO activities(title,short_description,activity_date,category,status,url,sort_order,visible) VALUES(?,?,?,?,?,?,?,?)').run(a.title,a.short_description,a.activity_date,a.category,a.status,a.url,a.sort_order,a.visible?1:0);audit(req,'activity_created','activities',a.title);res.status(201).json({id:i.lastInsertRowid})});
manage.put('/activities/:id',allow('activities'),validate(activitySchema),(req,res)=>{const a=req.body,i=db.prepare("UPDATE activities SET title=?,short_description=?,activity_date=?,category=?,status=?,url=?,sort_order=?,visible=?,updated_at=datetime('now') WHERE id=?").run(a.title,a.short_description,a.activity_date,a.category,a.status,a.url,a.sort_order,a.visible?1:0,req.params.id);if(!i.changes)return res.status(404).json({error:'Activity not found'});audit(req,'activity_updated','activities',a.title);res.json({ok:true})});
manage.delete('/activities/:id',allow('activities'),(req,res)=>{const a=db.prepare('SELECT title FROM activities WHERE id=?').get(req.params.id);if(!a)return res.status(404).json({error:'Activity not found'});db.prepare('DELETE FROM activities WHERE id=?').run(req.params.id);audit(req,'activity_deleted','activities',a.title);res.status(204).end()});

const regStatus=z.enum(['NEW','REVIEWING','ACCEPTED','REJECTED']);
manage.get('/registrations',allow('registrations:read'),(req,res)=>{let sql='SELECT * FROM registrations WHERE 1=1',p=[];if(req.query.status&&req.query.status!=='ALL'){sql+=' AND status=?';p.push(req.query.status)}if(req.query.q){const q='%'+String(req.query.q)+'%';sql+=' AND (name LIKE ? OR email LIKE ? OR college LIKE ? OR skills LIKE ? OR interests LIKE ?)';p.push(q,q,q,q,q)}sql+=' ORDER BY id DESC';res.json(db.prepare(sql).all(...p))});
manage.patch('/registrations/:id',allow('registrations:read'),validate(z.object({status:regStatus})),(req,res)=>{const r=db.prepare('SELECT name FROM registrations WHERE id=?').get(req.params.id);if(!r)return res.status(404).json({error:'Registration not found'});db.prepare("UPDATE registrations SET status=?,updated_at=datetime('now') WHERE id=?").run(req.body.status,req.params.id);audit(req,'registration_status','registrations',r.name+' → '+req.body.status);res.json({ok:true})});
manage.delete('/registrations/:id',allow('registrations'),(req,res)=>{db.prepare('DELETE FROM registrations WHERE id=?').run(req.params.id);audit(req,'registration_deleted','registrations',String(req.params.id));res.status(204).end()});
manage.get('/registrations.csv',allow('registrations:read'),(_,res)=>{const rows=db.prepare('SELECT * FROM registrations ORDER BY id DESC').all();const cols=['id','name','email','phone','department','year','college','usn','skills','interests','why_join','message','status','created_at'];const esc=v=>'"'+String(v??'').replace(/"/g,'""').replace(/^([=+\-@])/,"'$1")+'"';res.type('text/csv').send([cols.join(','),...rows.map(r=>cols.map(c=>esc(r[c])).join(','))].join('\n'))});

const teamSchema=z.object({name:z.string().min(1).max(100),role:z.string().min(1).max(100),description:z.string().max(500).default(''),image:z.string().max(500).default(''),linkedin:z.string().max(500).default(''),instagram:z.string().max(500).default(''),email:z.string().email().max(160).or(z.literal('')).default(''),github:z.string().max(500).default(''),sort_order:z.coerce.number().int().min(0).default(0),active:z.boolean().default(true)});
manage.get('/team',allow('team'),(_,res)=>res.json(db.prepare('SELECT * FROM team_members ORDER BY sort_order,id').all()));
manage.post('/team',allow('team'),validate(teamSchema),(req,res)=>{const m=req.body,i=db.prepare('INSERT INTO team_members(name,role,description,image,linkedin,instagram,email,github,sort_order,active) VALUES(?,?,?,?,?,?,?,?,?,?)').run(m.name,m.role,m.description,m.image,m.linkedin,m.instagram,m.email||null,m.github,m.sort_order,m.active?1:0);audit(req,'team_member_created','team',m.name);res.status(201).json({id:i.lastInsertRowid})});
manage.put('/team/:id',allow('team'),validate(teamSchema),(req,res)=>{const m=req.body;db.prepare("UPDATE team_members SET name=?,role=?,description=?,image=?,linkedin=?,instagram=?,email=?,github=?,sort_order=?,active=?,updated_at=datetime('now') WHERE id=?").run(m.name,m.role,m.description,m.image,m.linkedin,m.instagram,m.email||null,m.github,m.sort_order,m.active?1:0,req.params.id);audit(req,'team_member_updated','team',m.name);res.json({ok:true})});
manage.delete('/team/:id',allow('team'),(req,res)=>{db.prepare('DELETE FROM team_members WHERE id=?').run(req.params.id);audit(req,'team_member_deleted','team',String(req.params.id));res.status(204).end()});
manage.patch('/team/:id/active',allow('team'),validate(z.object({active:z.boolean()})),(req,res)=>{db.prepare("UPDATE team_members SET active=?,updated_at=datetime('now') WHERE id=?").run(req.body.active?1:0,req.params.id);res.json({ok:true})});

const contentKeys=new Set(['about_title','about_text','hero_subtitle','announcement_text','announcement_active','contact_email','contact_location','contact_instagram','contact_linkedin','contact_github']);
manage.get('/content',allow('content'),(_,res)=>{const o={};db.prepare('SELECT key,value FROM site_content').all().forEach(r=>o[r.key]=r.value);res.json(o)});
manage.put('/content',allow('content'),(req,res)=>{for(const[k,v]of Object.entries(req.body)){if(!contentKeys.has(k))return res.status(400).json({error:'Unsupported content field'});db.prepare("INSERT INTO site_content(key,value,updated_at) VALUES(?,?,datetime('now')) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(k,typeof v==='boolean'?(v?'1':'0'):String(v??'').slice(0,5000))}audit(req,'content_updated','content',Object.keys(req.body).join(', '));res.json({ok:true})});

manage.get('/logs',allow('logs'),(req,res)=>res.json(db.prepare('SELECT * FROM activity_logs ORDER BY id DESC LIMIT ?').all(Math.min(Number(req.query.limit)||100,200))));

const adminSchema=z.object({name:z.string().min(2).max(100),email:z.string().email().max(160),role:z.enum(ROLES),status:z.enum(['ACTIVE','INACTIVE']),profile_image:z.string().max(500).default('')});
manage.get('/admins',allow('admins'),(_,res)=>res.json(db.prepare('SELECT id,name,email,role,status,profile_image,created_at,last_login_at FROM admins ORDER BY id').all()));
manage.post('/admins',allow('admins'),validate(adminSchema.extend({password:z.string().min(12).max(200)})),(req,res)=>{const a=req.body;if(db.prepare('SELECT id FROM admins WHERE email=? COLLATE NOCASE').get(a.email))return res.status(409).json({error:'Admin already exists'});const i=db.prepare('INSERT INTO admins(name,email,password_hash,role,status,profile_image) VALUES(?,?,?,?,?,?)').run(a.name,a.email,bcrypt.hashSync(a.password,12),a.role,a.status,a.profile_image);audit(req,'admin_created','admins',a.email);res.status(201).json({id:i.lastInsertRowid})});
manage.put('/admins/:id',allow('admins'),validate(adminSchema.partial()),(req,res)=>{const a=req.body;const sets=[],p=[];for(const k of ['name','email','role','status','profile_image'])if(a[k]!==undefined){sets.push(k+'=?');p.push(a[k])}if(!sets.length)return res.json({ok:true});p.push(req.params.id);db.prepare("UPDATE admins SET "+sets.join(',')+",updated_at=datetime('now'),session_version=session_version+1 WHERE id=?").run(...p);audit(req,'admin_updated','admins',String(req.params.id));res.json({ok:true})});
manage.delete('/admins/:id',allow('admins'),(req,res)=>{if(String(req.params.id)===String(req.admin.sub))return res.status(400).json({error:'Cannot delete yourself'});db.prepare('DELETE FROM admins WHERE id=?').run(req.params.id);audit(req,'admin_deleted','admins',String(req.params.id));res.status(204).end()});
manage.get('/settings',allow('settings'),(req,res)=>{const a=db.prepare('SELECT id,name,email,role,profile_image,status,created_at,last_login_at FROM admins WHERE id=?').get(req.admin.sub);res.json(a)});
manage.put('/settings/profile',allow('settings'),validate(z.object({name:z.string().min(2).max(100),email:z.string().email(),profile_image:z.string().max(500).default('')})),(req,res)=>{db.prepare("UPDATE admins SET name=?,email=?,profile_image=?,updated_at=datetime('now') WHERE id=?").run(req.body.name,req.body.email,req.body.profile_image,req.admin.sub);res.json({ok:true})});
manage.put('/settings/password',allow('settings'),validate(z.object({current_password:z.string(),new_password:z.string().min(12).max(200)})),(req,res)=>{const a=db.prepare('SELECT password_hash FROM admins WHERE id=?').get(req.admin.sub);if(!a||!bcrypt.compareSync(req.body.current_password,a.password_hash))return res.status(400).json({error:'Current password is incorrect'});db.prepare("UPDATE admins SET password_hash=?,session_version=session_version+1 WHERE id=?").run(bcrypt.hashSync(req.body.new_password,12),req.admin.sub);res.json({ok:true})});

const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:4*1024*1024,files:10}});
manage.post('/upload',allow('events'),upload.array('file',10),(req,res)=>{const urls=[];for(const f of req.files||[]){let ext=f.mimetype==='image/png'?'png':f.mimetype==='image/webp'?'webp':f.mimetype==='image/jpeg'?'jpg':null;if(!ext)return res.status(400).json({error:'Only JPEG, PNG and WebP images are allowed'});const n=crypto.randomBytes(16).toString('hex')+'.'+ext;fs.writeFileSync(path.join(uploadDir,n),f.buffer);urls.push('/uploads/'+n)}res.status(201).json({urls,url:urls[0]})});

api.use('/manage',manage);
api.get('/health',(_,res)=>res.json({ok:true}));
api.get('/leadership',(_,res)=>res.json(db.prepare('SELECT * FROM team_members WHERE active=1 ORDER BY sort_order,id').all()));
api.get('/events',(_,res)=>res.json(db.prepare('SELECT * FROM events WHERE published=1 ORDER BY event_date DESC,id DESC').all().map(eventOut)));
api.get('/events/:slug',(req,res)=>{const r=db.prepare('SELECT * FROM events WHERE slug=? AND published=1').get(req.params.slug);if(!r)return res.status(404).json({error:'Event not found'});res.json(eventOut(r))});
api.get('/activities',(_,res)=>res.json(db.prepare('SELECT * FROM activities WHERE visible=1 ORDER BY sort_order,id').all()));
api.get('/content',(_,res)=>{const o={};db.prepare('SELECT key,value FROM site_content').all().forEach(r=>o[r.key]=r.value);res.json(o)});
api.get('/stats',(_,res)=>res.json({events:db.prepare('SELECT COUNT(*) c FROM events WHERE published=1').get().c,activities:db.prepare('SELECT COUNT(*) c FROM activities WHERE visible=1').get().c,leaders:db.prepare('SELECT COUNT(*) c FROM team_members WHERE active=1').get().c,registrations:db.prepare('SELECT COUNT(*) c FROM registrations').get().c}));
const joinLimiter=rateLimit({windowMs:15*60*1000,limit:10,standardHeaders:'draft-8',legacyHeaders:false});
const joinSchema=z.object({name:z.string().min(2).max(80),email:z.string().email().max(160),phone:z.string().max(30).default(''),department:z.string().max(120).default('CSE'),year:z.coerce.number().int().min(1).max(4).optional(),college:z.string().max(160).default(''),usn:z.string().max(30).default(''),skills:z.string().max(500).default(''),interests:z.string().max(500).default(''),why_join:z.string().max(1000).default(''),message:z.string().max(1000).default(''),website:z.string().max(0).optional()});
api.post('/join',joinLimiter,validate(joinSchema),(req,res)=>{if(req.body.website)return res.status(201).json({ok:true});const d=req.body;if(db.prepare("SELECT 1 FROM registrations WHERE email=? AND created_at>datetime('now','-1 day')").get(d.email))return res.status(409).json({error:'You already applied today. We will reach out soon.'});db.prepare('INSERT INTO registrations(name,email,phone,department,year,college,usn,skills,interests,why_join,message) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(d.name,d.email,d.phone,d.department,d.year??null,d.college,d.usn,d.skills,d.interests,d.why_join,d.message);res.status(201).json({ok:true,message:'Application received. Welcome to CIPHER.'})});
module.exports=api;